### ISSUE TITLE
Implement user authentication

### ISSUE THREAD

**Issue by Chr728** [JamesPartsafas/online-store#10]
Initiator - User

Story points: 5
Risk: High
Priority: High

As a user, I want to be able to create an account or log in to my account so that I can have my information handy upon purchasing.

See story #9 for the parent issue.

1. [x] The site needs to authenticate the user, you should decide the information you want to have to identify each user , ( do you want to identify each user by email and password, or the username and password ?) it should be determined.
2. [x] if the user is a new customer then direct the user to the sign-up page, decide what type of information you want to store in the profile of each user ( first name, family name, email, password, phone number, address, subscription to our newsletter, subscription to get our weekly deals.... etc) all these information should be determined at this stage.
3. [x] decide the alerts that the user sees when:   
       a. the user is not a previous customer and decide to sign in ( what should pop up if he tries to do that before directing to sign up 
       page)
       b. if the user's credentials are wrong  what alert or message should be displayed

Child tasks are: #48 #49 #52 #55 #66 #73 #74

Acceptance test
- Upon visiting the site, visit the registration page
- Submitting the form with missing data of mismatched passwords will have an error displayed to the user.
- Submitting the form with all information and matching passwords will have an account created and the user logged in. The user is redirected to the home page.
- Upon being logged in, attempting to visit the login or register pages must result in a redirect to the home page.
- When the logout button is clicked, the user is logged out.
- Upon visiting the login page and entering valid credentials, the user must be logged in again.

**Comment by JamesPartsafas** [comment]
All child tasks are complete. The story can be closed.
