### ISSUE TITLE
Allow user to modify quantity in cart page

### ISSUE THREAD

**Issue by Chr728** [JamesPartsafas/online-store#111]
Initiator - signed-in users

As a signed-in user, I want to be able to modify the  quanitiy of items in  my cart in case I change my mind on the quantity of the item I want to buy.

Story points: 2
Risk: Low
Priority: Medium

Users, after signing in, should be able to modify the quantity of the items in their cart, and view the updated price and the total overall price change after changing the quantity.

Tasks:

- [x] access the quantity from the local storage
- [x] have the buttons to increment of decrement the quantity
- [x] finish the style of the cart page 

epic story #31 

Acceptance test steps:

1. go to cart page
2. change the quantity of the item 
3. the quantity should be updated right away on the site
4. check if the subtotal and overall total reflect the new changes made on quantity

**Comment by JamesPartsafas** [comment]
Related pull request has been merged.
