### ISSUE TITLE
Polish code to adhere to conventions

### ISSUE THREAD

**Issue by janong24** [JamesPartsafas/online-store#126]
See code conventions in Wiki for style guide.

Story points: 1

### Backend ###
- [x] controllers
- [x] seeders
- [x] models
- [x] tests
- [x] factories
- [x] migrations
- [x] routes

### Frontend ###
- [x] main layout
- [x] blades
- [x] CSS
- [x] JS

**Comment by janong24** [comment]
Is DatabaseSeeder.php being used?

**Comment by JamesPartsafas** [comment]
> Is DatabaseSeeder.php being used?

No, it is not. It is simply provided by the Laravel Framework as an example of how a seeder should be structured. It should be safe to remove.

**Comment by janong24** [comment]
> > Is DatabaseSeeder.php being used?
> 
> No, it is not. It is simply provided by the Laravel Framework as an example of how a seeder should be structured. It should be safe to remove.

Noted, thanks!
