### ISSUE TITLE
Create  product pages for front end 

### ISSUE THREAD

**Issue by Chr728** [JamesPartsafas/online-store#54]
Parent story: #34 and its epic parent is #9

Story points: 3
Priority: High
Risk: Low
As a visitor to the site, I want to be able to view the detailed information about  products, look at their pictures and be able to add them to my cart with desired quantity I wish so that I can buy products I wish.

The page should display information about the product, including image and description.

Tasks:

1. Design and  set up the  database for products
2. Write the code to  retrieve the information from the database
3. Write the front end code to display the information about each product on the website 
4. link this page to cart

**Comment by boyang9602** [comment]
- [ ] Task 1
