### ISSUE TITLE
Core user story: Browse site

### ISSUE THREAD

**Issue by Chr728** [JamesPartsafas/online-store#9]
Initiator - site visitor

As a visitor to the site, I want to be able to browse products offered so that I can purchase any that I need or find interesting.

Story points: 15
Risk: High
Priority: High

1. Create a special feature that can make the user/customer view the list of all products that exist on the website.
2. It should be visibly easy to use for the user and display the product in an organized nice way.
3. should decide how many products you want to display per page ( decide the limit of the number of products per page, do you want to display 10 products per page for example ?). 

Child tasks are: #25 #32 #10 #24 #34 #40 #51 #52 #53 #56

**Comment by janong24** [comment]
All bugs, tasks, and substories resolved.
